---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-demo-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v1
  labels:
    app: webapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      serviceAccountName: azure-demo-webapp
      containers:
      - name: webapp
        image: crwebdemo.azurecr.io/webappdemo:1.0.0
        imagePullPolicy: Always
        ports:
            - containerPort: 80
              protocol: TCP
---